name: ai_filtering
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+22
  before_after: ^2.1.0
  liquid_progress_indicator: ^0.3.2
  image_cropper: ^1.3.1
  image_size_getter: ^0.2.1
  photo_view: ^0.10.3
  image_gallery_saver: '^1.6.8'
  tflite: ^1.1.1
  image: ^3.0.1
  image_pixels: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  
  uses-material-design: true

  assets: 
    - assets/
    - assets/images/
    - assets/models/


